export const DEMO_SCHEMAS = {
  "W2": [
    { name: "employer_name", type: "string" },
    { name: "employer_ein", type: "string" },
    { name: "employee_name", type: "string" },
    { name: "employee_ssn", type: "string" },
    { name: "wages_tips_compensation", type: "number" },
    { name: "federal_income_tax_withheld", type: "number" },
    { name: "social_security_wages", type: "number" },
    { name: "social_security_tax_withheld", type: "number" },
    { name: "medicare_wages", type: "number" },
    { name: "medicare_tax_withheld", type: "number" },
    { name: "tax_year", type: "string" },
  ],
  "Payslip": [
    { name: "employee_name", type: "string" },
    { name: "pay_period_start", type: "date" },
    { name: "pay_period_end", type: "date" },
    { name: "gross_pay", type: "number" },
    { name: "net_pay", type: "number" },
    { name: "employer_name", type: "string" },
    { name: "pay_date", type: "date" },
    { name: "ytd_gross", type: "number" },
    { name: "ytd_net", type: "number" },
  ],
  "Bank-Statement": [
    { name: "account_holder_name", type: "string" },
    { name: "account_number", type: "string" },
    { name: "bank_name", type: "string" },
    { name: "statement_period_start", type: "date" },
    { name: "statement_period_end", type: "date" },
    { name: "beginning_balance", type: "number" },
    { name: "ending_balance", type: "number" },
    { name: "total_deposits", type: "number" },
    { name: "total_withdrawals", type: "number" },
  ],
  "1040-Document": [
    { name: "filing_status", type: "string" },
    { name: "taxpayer_name", type: "string" },
    { name: "taxpayer_ssn", type: "string" },
    { name: "spouse_name", type: "string" },
    { name: "spouse_ssn", type: "string" },
    { name: "adjusted_gross_income", type: "number" },
    { name: "taxable_income", type: "number" },
    { name: "total_tax", type: "number" },
    { name: "tax_year", type: "string" },
  ],
  "US-Passport": [
    { name: "full_name", type: "string" },
    { name: "date_of_birth", type: "date" },
    { name: "passport_number", type: "string" },
    { name: "issue_date", type: "date" },
    { name: "expiration_date", type: "date" },
    { name: "nationality", type: "string" },
    { name: "sex", type: "string" },
  ],
};
