/**
 * App entry point - router, layout, view lifecycle.
 *
 * Each view exports mount(root) and unmount(root).
 * Only one content view is in the DOM at a time.
 */
import * as Session from "./utils/session.js";
import * as Toast from "./utils/toast.js";
import * as TenantContext from "./utils/tenant-context.js";
import * as CollapsibleFilterBar from "./utils/collapsible-filter-bar.js";
import * as HttpClient from "./services/http.js";
import * as Auth from "./services/auth.js";
import * as Audit from "./services/audit.js";

import BADGES from "./badges.json";

const _now = new Date();
function getBadge(view) {
  const cfg = BADGES[view];
  if (!cfg || _now >= new Date(cfg.expiry)) return null;
  return cfg;
}

import pendingHtml from "./views/pending/pending.html";
import dashboardHtml from "./views/sidebar/sidebar.html";
import { tpl } from "./utils/tpl.js";

const pendingTmpl = tpl(pendingHtml);
const dashboardTmpl = tpl(dashboardHtml);

import * as KeysView from "./views/keys/keys.js";
import * as ExtractionRulesView from "./views/extraction-rules/extraction-rules.js";
import * as SchemasService from "./services/schemas.js";
import * as Store from "./state/blueprint-store.js";
import * as UsersView from "./views/users/users.js";
import * as TenantsView from "./views/tenants/tenants.js";
import * as DocumentCategoriesView from "./views/document-categories/document-categories.js";
import * as AuditLogView from "./views/audit-log/audit-log.js";
import * as DocumentsView from "./views/documents/documents.js";
import * as DocumentSearchView from "./views/document-search/document-search.js";
import * as UsageView from "./views/usage/usage.js";
import * as MetricsView from "./views/metrics/metrics.js";
import * as LoginView from "./views/login/login.js";

// Configuration - loaded from config.json (generated by infra-deploy)
let CONFIG = {
  apiUrl: "",
  cognitoUserPoolId: "",
  cognitoClientId: "",
  cognitoDomain: null,
  googleEnabled: false,
};

async function loadConfig() {
  try {
    const response = await fetch("config.json");
    const outputs = await response.json();
    CONFIG.apiUrl = outputs.api_endpoint?.value || "";
    CONFIG.cognitoUserPoolId = outputs.cognito_user_pool_id?.value || "";
    CONFIG.cognitoClientId = outputs.cognito_client_id?.value || "";
    CONFIG.cognitoDomain = outputs.cognito_domain?.value || null;
    CONFIG.googleEnabled = outputs.cognito_google_enabled?.value === true;
  } catch {
    CONFIG.apiUrl = "http://localhost:8000";
  }
}

// --- App state ---
const app = document.getElementById("app");
let _currentView = null;
let _mainContent = null;

// View registry: name -> { module, lazyLoad }
const VIEWS = {
  keys: { module: KeysView },
  users: { module: UsersView },
  tenants: { module: TenantsView },
  "extraction-rules": { module: ExtractionRulesView },
  "doc-categories": { module: DocumentCategoriesView },
  "audit-log": { module: AuditLogView },
  documents: { module: DocumentsView },
  "document-search": { module: DocumentSearchView },
  usage: { module: UsageView },
  metrics: { module: MetricsView },
};

// --- Screen management ---

function showLogin() {
  LoginView.mount(app, {
    googleEnabled: CONFIG.googleEnabled,
    cognitoDomain: CONFIG.cognitoDomain,
    cognitoClientId: CONFIG.cognitoClientId,
    redirectUri: window.location.origin + "/callback",
  });
}

function showPending(email) {
  app.replaceChildren(pendingTmpl());
  app.querySelector("#pending-email").textContent = email;
  app.querySelector("#pending-logout-btn").addEventListener("click", logout);
}

function showDashboard(session) {
  HttpClient.configure({ baseUrl: CONFIG.apiUrl, jwt: session.idToken, apiKey: "" });
  app.replaceChildren(dashboardTmpl());
  _mainContent = app.querySelector("#main-content");
  app.querySelectorAll("[id$='-nav-badge']").forEach((b) => {
    const view = b.id.replace("-nav-badge", "");
    const cfg = getBadge(view);
    if (!cfg) {
      b.remove();
      return;
    }
    b.textContent = cfg.label;
    b.className = `nav-badge-${cfg.variant}`;
  });

  app.querySelectorAll(".nav-section").forEach((section) => {
    const hasActiveBadge = [...section.querySelectorAll(".nav-item")].some((item) =>
      getBadge(item.dataset.view),
    );
    if (!hasActiveBadge) return;
    const header = section.querySelector(".nav-section-header");
    if (header && !header.querySelector(".nav-section-badge-dot")) {
      const dot = document.createElement("span");
      dot.className = "nav-section-badge-dot";
      header.appendChild(dot);
    }
  });

  // Connected info
  app.querySelector("#connected-url").textContent = session.email;

  // Kick off tenant list fetch so it's cached before views mount
  TenantContext.load();

  // Super-admin nav visibility
  const isSuper = Session.isSuperAdmin();
  const usersNav = app.querySelector("#nav-section-users");
  if (usersNav) usersNav.classList.toggle("hidden", !isSuper);
  const tenantsNav = app.querySelector("#nav-section-tenants");
  if (tenantsNav) tenantsNav.classList.toggle("hidden", !isSuper);

  // Sidebar section toggles
  app.querySelectorAll(".nav-section-header").forEach((/** @type {HTMLElement} */ header) => {
    header.addEventListener("click", () => {
      const section = header.dataset.section;
      const body = app.querySelector(`#section-${section}`);
      const arrow = header.querySelector(".nav-arrow");
      const isOpen = !body.classList.contains("hidden");
      if (isOpen) {
        body.classList.add("hidden");
        arrow.textContent = "▸";
        header.classList.remove("active");
      } else {
        body.classList.remove("hidden");
        arrow.textContent = "▾";
        header.classList.add("active");
      }
    });
  });

  // Nav item clicks
  app.querySelectorAll(".nav-item").forEach((/** @type {HTMLElement} */ item) => {
    item.addEventListener("click", () => activateNavItem(item.dataset.view));
  });

  // Logout
  app.querySelector("#logout-btn").addEventListener("click", logout);

  // Mobile bottom nav direct items
  app.querySelectorAll(".mobile-nav-item[data-view]").forEach((item) => {
    item.addEventListener("click", () => activateNavItem(item.dataset.view));
  });

  // Mobile fullscreen overlay (More)
  const overlay = app.querySelector("#mobile-menu-overlay");
  const closeOverlay = () => overlay?.classList.remove("open");
  app.querySelector("#mobile-more-btn")?.addEventListener("click", () => overlay?.classList.toggle("open"));
  app.querySelector("#mobile-menu-close")?.addEventListener("click", closeOverlay);
  app.querySelector("#logout-btn-mobile-menu")?.addEventListener("click", logout);
  app.querySelectorAll(".mobile-menu-item[data-view]").forEach((item) => {
    item.addEventListener("click", () => { closeOverlay(); activateNavItem(item.dataset.view); });
  });
  if (Session.isSuperAdmin()) {
    app.querySelector("#mobile-menu-admin")?.classList.remove("hidden");
  }

  // Restore view from hash (no default - sidebar starts collapsed)
  const initialHash = location.hash.replace("#", "");
  const initialView = initialHash.split("/")[0];
  if (VIEWS[initialView]) activateNavItem(initialView);

  // Preload blueprint schemas so extraction-rules view renders instantly
  SchemasService.getAllFields()
    .then((data) => {
      Store.set({ schemas: SchemasService.groupFieldsByDocType(data), schemasLoading: false });
    })
    .catch(() => Store.set({ schemasLoading: false }));
}

function navigateTo(viewName) {
  if (_currentView && _currentView.unmount) {
    _currentView.unmount(_mainContent);
  }

  // Clear actions before mounting new view
  const viewActions = document.querySelector("#view-actions");
  if (viewActions) viewActions.replaceChildren();

  const entry = VIEWS[viewName];

  if (!entry) return;

  // Preserve sub-path if navigating to the same view (e.g. extraction-rules/pay_stub)
  const currentBase = location.hash.replace("#", "").split("/")[0];
  if (currentBase !== viewName) {
    location.hash = viewName;
  }
  entry.module.mount(_mainContent);
  _currentView = entry.module;
  CollapsibleFilterBar.attach();
}

function activateNavItem(viewName) {
  const navItem = app.querySelector(`[data-view="${viewName}"]`);
  if (!navItem) return;

  app.querySelectorAll(".nav-item").forEach((i) => i.classList.remove("active"));
  navItem.classList.add("active");

  // Sync mobile bottom nav active state
  app.querySelectorAll(".mobile-nav-item").forEach((i) => i.classList.remove("active"));
  app.querySelector(`.mobile-nav-item[data-view="${viewName}"]`)?.classList.add("active");
  app.querySelectorAll(".mobile-menu-item").forEach((i) => i.classList.remove("active"));
  app.querySelector(`.mobile-menu-item[data-view="${viewName}"]`)?.classList.add("active");

  // Expand parent section
  const sectionBody = navItem.closest(".nav-section-body");
  if (sectionBody) {
    sectionBody.classList.remove("hidden");
    const header = sectionBody.previousElementSibling;
    if (header) {
      const arrow = header.querySelector(".nav-arrow");
      if (arrow) arrow.textContent = "▾";
      header.classList.add("active");
    }
  }

  const title = app.querySelector("#view-title");
  if (title) {
    title.textContent = (navItem.dataset.title || navItem.textContent).trim();
    const badgeCfg = getBadge(viewName);
    if (badgeCfg) {
      const badge = document.createElement("span");
      badge.className = `nav-badge-${badgeCfg.variant}`;
      badge.textContent = badgeCfg.label;
      title.appendChild(badge);
    }
  }
  navigateTo(viewName);
}

window.addEventListener("hashchange", () => {
  const viewName = location.hash.replace("#", "").split("/")[0];
  if (VIEWS[viewName] && _mainContent && _currentView !== VIEWS[viewName].module)
    activateNavItem(viewName);
});

// --- Auth flow ---

function routeAfterLogin(session) {
  if (!Session.isApproved()) {
    showPending(session.email);
    return;
  }
  showDashboard(session);
}

async function logout() {
  const session = Session.get();
  if (session?.accessToken) {
    Audit.reportLogout(session.email);
    try {
      await Auth.signOut(session.accessToken);
    } catch {
      // ignore signout errors
    }
  }
  Session.clear();
  showLogin();
}

// --- Init ---

async function init() {
  await loadConfig();
  Auth.configure(CONFIG.cognitoUserPoolId, CONFIG.cognitoClientId);

  // Handle OAuth callback (Google SSO redirect)
  const isCallback = window.location.pathname === "/callback";
  const params = new URLSearchParams(window.location.search);
  const authCode = params.get("code");
  const returnedState = params.get("state");
  if (isCallback && authCode && CONFIG.cognitoDomain) {
    const savedState = sessionStorage.getItem("oauth_state");
    const codeVerifier = sessionStorage.getItem("oauth_code_verifier");
    sessionStorage.removeItem("oauth_state");
    sessionStorage.removeItem("oauth_code_verifier");

    if (!savedState || savedState !== returnedState) {
      console.error("OAuth state mismatch - possible CSRF");
      window.history.replaceState({}, "", "/");
      showLogin();
      return;
    }

    try {
      const tokens = await Auth.exchangeCodeForTokens(
        authCode,
        CONFIG.cognitoDomain,
        CONFIG.cognitoClientId,
        window.location.origin + "/callback",
        codeVerifier,
      );
      Session.save({
        accessToken: tokens.access_token,
        idToken: tokens.id_token,
        refreshToken: tokens.refresh_token,
        expiresIn: tokens.expires_in,
        email: tokens.email,
      });
      window.history.replaceState({}, "", "/");
      routeAfterLogin(Session.get());
      Audit.reportLogin(tokens.email);
      return;
    } catch (e) {
      console.error("OAuth callback failed:", e);
      window.history.replaceState({}, "", "/");
    }
  }

  const session = Session.get();
  if (session && !Session.isExpired()) {
    routeAfterLogin(session);
  } else {
    Session.clear();
    showLogin();
  }
}

// Login callback
LoginView.onLoginSuccess(() => {
  const session = Session.get();
  routeAfterLogin(session);
  Audit.reportLogin(session.email);
});

// Session expiry
Session.onExpire(() => {
  showLogin();
  Toast.show("Session expired due to inactivity");
});

init();
