/**
 * App entry point - router, layout, view lifecycle.
 *
 * Each view exports mount(root) and unmount(root).
 * Only one content view is in the DOM at a time.
 */
import * as Session from "./utils/session.js";
import * as Toast from "./utils/toast.js";
import * as TenantContext from "./utils/tenant-context.js";
import * as HttpClient from "./services/http.js";
import * as Auth from "./services/auth.js";

import pendingHtml from "./views/pending/pending.html";
import dashboardHtml from "./views/sidebar/sidebar.html";
import { tpl } from "./utils/tpl.js";

const pendingTmpl = tpl(pendingHtml);
const dashboardTmpl = tpl(dashboardHtml);

import * as KeysView from "./views/keys/keys.js";
import * as ExtractionRulesView from "./views/extraction-rules/extraction-rules.js";
import * as UsersView from "./views/users/users.js";
import * as TenantsView from "./views/tenants/tenants.js";
import * as DocumentCategoriesView from "./views/document-categories/document-categories.js";
import * as AuditLogView from "./views/audit-log/audit-log.js";
import * as DocumentsView from "./views/documents/documents.js";
import * as TestDocumentsView from "./views/test-documents/test-documents.js";
import * as LoginView from "./views/login/login.js";

// Configuration - loaded from config.json (generated by infra-deploy)
let CONFIG = {
  apiUrl: "",
  cognitoUserPoolId: "",
  cognitoClientId: "",
};

async function loadConfig() {
  try {
    const response = await fetch("config.json");
    const outputs = await response.json();
    CONFIG.apiUrl = outputs.api_endpoint?.value || "";
    CONFIG.cognitoUserPoolId = outputs.cognito_user_pool_id?.value || "";
    CONFIG.cognitoClientId = outputs.cognito_client_id?.value || "";
  } catch {
    CONFIG.apiUrl = "http://localhost:8000";
  }
}

// --- App state ---
const app = document.getElementById("app");
let _currentView = null;
let _mainContent = null;

// View registry: name → { module, lazyLoad }
const VIEWS = {
  keys: { module: KeysView },
  users: { module: UsersView },
  tenants: { module: TenantsView },
  "extraction-rules": { module: ExtractionRulesView },
  "doc-categories": { module: DocumentCategoriesView },
  "audit-log": { module: AuditLogView },
  documents: { module: DocumentsView },
  "test-documents": { module: TestDocumentsView },
};

// --- Screen management ---

function showLogin() {
  LoginView.mount(app);
}

function showPending(email) {
  app.replaceChildren(pendingTmpl());
  app.querySelector("#pending-email").textContent = email;
  app.querySelector("#pending-logout-btn").addEventListener("click", logout);
}

function showDashboard(session) {
  HttpClient.configure({ baseUrl: CONFIG.apiUrl, jwt: session.idToken, apiKey: "" });
  app.replaceChildren(dashboardTmpl());
  _mainContent = app.querySelector("#main-content");

  // Connected info
  app.querySelector("#connected-url").textContent = session.email;

  // Tenant context
  TenantContext.init(app.querySelector("#global-tenant-select"));
  TenantContext.load();

  // Super-admin nav visibility
  const isSuper = Session.isSuperAdmin();
  const usersNav = app.querySelector("#nav-section-users");
  if (usersNav) usersNav.classList.toggle("hidden", !isSuper);
  const tenantsNav = app.querySelector("#nav-section-tenants");
  if (tenantsNav) tenantsNav.classList.toggle("hidden", !isSuper);

  // Sidebar section toggles
  app.querySelectorAll(".nav-section-header").forEach((/** @type {HTMLElement} */ header) => {
    header.addEventListener("click", () => {
      const section = header.dataset.section;
      const body = app.querySelector(`#section-${section}`);
      const arrow = header.querySelector(".nav-arrow");
      const isOpen = !body.classList.contains("hidden");
      if (isOpen) {
        body.classList.add("hidden");
        arrow.textContent = "▸";
        header.classList.remove("active");
      } else {
        body.classList.remove("hidden");
        arrow.textContent = "▾";
        header.classList.add("active");
      }
    });
  });

  // Nav item clicks
  app.querySelectorAll(".nav-item").forEach((/** @type {HTMLElement} */ item) => {
    item.addEventListener("click", () => {
      app.querySelectorAll(".nav-item").forEach((i) => i.classList.remove("active"));
      item.classList.add("active");
      const title = app.querySelector("#view-title");
      if (title) title.textContent = item.textContent.trim();
      navigateTo(item.dataset.view);
    });
  });

  // Logout
  app.querySelector("#logout-btn").addEventListener("click", logout);

  // Default view
  const defaultTitle = app.querySelector("#view-title");
  if (defaultTitle) defaultTitle.textContent = "API Keys";
  navigateTo("keys");
}

function navigateTo(viewName) {
  if (_currentView && _currentView.unmount) {
    _currentView.unmount(_mainContent);
  }

  // Clear actions before mounting new view
  const viewActions = document.querySelector("#view-actions");
  if (viewActions) viewActions.replaceChildren();

  const entry = VIEWS[viewName];
  if (!entry) return;

  entry.module.mount(_mainContent);
  _currentView = entry.module;
}

// --- Auth flow ---

function routeAfterLogin(session) {
  if (!Session.isApproved()) {
    showPending(session.email);
    return;
  }
  showDashboard(session);
}

async function logout() {
  const session = Session.get();
  if (session?.accessToken) {
    try {
      await Auth.signOut(session.accessToken);
    } catch {
      // ignore signout errors
    }
  }
  Session.clear();
  showLogin();
}

// --- Init ---

async function init() {
  await loadConfig();
  Auth.configure(CONFIG.cognitoUserPoolId, CONFIG.cognitoClientId);

  const session = Session.get();
  if (session && !Session.isExpired()) {
    routeAfterLogin(session);
  } else {
    Session.clear();
    showLogin();
  }
}

// Login callback
LoginView.onLoginSuccess(() => {
  const session = Session.get();
  routeAfterLogin(session);
});

// Session expiry
Session.onExpire(() => {
  showLogin();
  Toast.show("Session expired due to inactivity");
});

init();
