import os

from pydantic_settings import BaseSettings, SettingsConfigDict

# environment variable names
API_AUTH_INSECURE_SHARED_KEY = "API_AUTH_INSECURE_SHARED_KEY"
BDA_PROFILE_ARN = "BDA_PROFILE_ARN"
BDA_PROJECT_ARN = "BDA_PROJECT_ARN"
BDA_REGION = "BDA_REGION"
BEDROCK_CLASSIFICATION_MODEL_ID_PARAM = "BEDROCK_CLASSIFICATION_MODEL_ID_PARAM"
BEDROCK_CLASSIFICATION_PROMPT_PARAM = "BEDROCK_CLASSIFICATION_PROMPT_PARAM"
DOCUMENTAI_DOCUMENT_METADATA_JOB_ID_INDEX_NAME = "DOCUMENTAI_DOCUMENT_METADATA_JOB_ID_INDEX_NAME"
DOCUMENTAI_DOCUMENT_METADATA_TABLE_NAME = "DOCUMENTAI_DOCUMENT_METADATA_TABLE_NAME"
DOCUMENTAI_INPUT_LOCATION = "DOCUMENTAI_INPUT_LOCATION"
DOCUMENTAI_OUTPUT_LOCATION = "DOCUMENTAI_OUTPUT_LOCATION"
EXTRACTION_RULES_TABLE_NAME = "EXTRACTION_RULES_TABLE_NAME"
MAX_BDA_INVOKE_RETRY_ATTEMPTS = "MAX_BDA_INVOKE_RETRY_ATTEMPTS"
API_AUTH_ENABLED = "API_AUTH_ENABLED"
API_AUTH_CACHE_TTL = "API_AUTH_CACHE_TTL"
API_KEYS_TABLE_NAME = "API_KEYS_TABLE_NAME"

# metrics pipeline
ATHENA_WORKGROUP_NAME = "ATHENA_WORKGROUP_NAME"
DDB_EXPORT_BUCKET_NAME = "DDB_EXPORT_BUCKET_NAME"
DDB_METRICS_INPUT_QUEUE_URL = "DDB_METRICS_INPUT_QUEUE_URL"
DDB_RAW_DATA_TABLE_NAME = "DDB_RAW_DATA_TABLE_NAME"
GLUE_DATABASE_NAME = "GLUE_DATABASE_NAME"


class PydanticBaseEnvConfig(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")


def get_required_env(name: str) -> str:
    value = os.getenv(name)

    if not value:
        raise ValueError(f"{name} environment variable not set")

    return value
