# DO NOT EDIT - generated by `uv run tasks.py generate-categories`
# Source of truth: infra/document-types/ folder names
from enum import StrEnum


class PreclassificationCategory(StrEnum):
    ASSETS = "assets"
    EXPENSES = "expenses"
    IDENTITY = "identity"
    INCOME = "income"
    SUPPORTING_RECORDS = "supporting_records"
