/**
 * App entry point — routing, layout, init.
 */
import * as Session from "./utils/session.js";
import * as Toast from "./utils/toast.js";
import * as TenantContext from "./utils/tenant-context.js";
import * as HttpClient from "./services/http.js";
import * as Auth from "./services/auth.js";
import * as KeysView from "./views/keys.js";
import * as BlueprintsView from "./views/blueprints.js";
import * as SearchView from "./views/search.js";
import * as UsersView from "./views/users.js";
import * as TenantsView from "./views/tenants.js";
import * as DocumentCategoriesView from "./views/document-categories.js";
import * as AuditLogView from "./views/audit-log.js";
import * as LoginView from "./views/login.js";

// Configuration — loaded from config.json (generated by infra-deploy)
let CONFIG = {
  apiUrl: "",
  cognitoUserPoolId: "",
  cognitoClientId: "",
};

async function loadConfig() {
  try {
    const response = await fetch("config.json");
    const outputs = await response.json();
    CONFIG.apiUrl = outputs.api_endpoint?.value || "";
    CONFIG.cognitoUserPoolId = outputs.cognito_user_pool_id?.value || "";
    CONFIG.cognitoClientId = outputs.cognito_client_id?.value || "";
  } catch {
    // Fall back to localhost for local dev
    CONFIG.apiUrl = "http://localhost:8000";
  }
}

// DOM refs
const loginView = document.getElementById("login-view");
const dashboardView = document.getElementById("dashboard-view");
const pendingView = document.getElementById("pending-view");
const connectedUrl = document.getElementById("connected-url");
const logoutBtn = document.getElementById("logout-btn");
const createKeyBtn = document.getElementById("create-key-btn");

// --- Views ---
function showView(view) {
  loginView.classList.add("hidden");
  dashboardView.classList.add("hidden");
  pendingView.classList.add("hidden");
  view.classList.remove("hidden");
}

function routeAfterLogin(session) {
  HttpClient.configure({ baseUrl: CONFIG.apiUrl, jwt: session.idToken, apiKey: CONFIG.dataApiKey || "" });
  if (!Session.isApproved()) {
    document.getElementById("pending-email").textContent = session.email;
    showView(pendingView);
    return false;
  }
  connectedUrl.textContent = session.email;

  // Reveal super-admin-only navigation
  const isSuper = Session.isSuperAdmin();
  const usersNav = document.getElementById("nav-section-users");
  if (usersNav) usersNav.classList.toggle("hidden", !isSuper);
  const tenantsNav = document.getElementById("nav-section-tenants");
  if (tenantsNav) tenantsNav.classList.toggle("hidden", !isSuper);

  showView(dashboardView);
  return true;
}

function showContentView(viewId) {
  document.querySelectorAll(".content-view").forEach((v) => v.classList.add("hidden"));
  document.getElementById(viewId).classList.remove("hidden");
}

// --- Init ---
async function init() {
  await loadConfig();
  Auth.configure(CONFIG.cognitoUserPoolId, CONFIG.cognitoClientId);
  TenantContext.init(document.getElementById("global-tenant-select"));

  const session = Session.get();
  if (session && !Session.isExpired()) {
    if (routeAfterLogin(session)) {
      KeysView.load();
      BlueprintsView.load();
      TenantContext.load();
    }
  } else {
    Session.clear();
    showView(loginView);
  }
}

init();
// --- Init view modules ---
KeysView.init({
  tbody: document.getElementById("keys-tbody"),
  noKeys: document.getElementById("no-keys"),
  createKeyBtn,
  createModal: document.getElementById("create-modal"),
  createForm: document.getElementById("create-form"),
  cancelCreate: document.getElementById("cancel-create"),
  keyCreatedModal: document.getElementById("key-created-modal"),
  newKeyValue: document.getElementById("new-key-value"),
  copyKeyBtn: document.getElementById("copy-key-btn"),
  closeCreated: document.getElementById("close-created"),
  refreshKeysBtn: document.getElementById("refresh-keys-btn"),
});

BlueprintsView.init({
  list: document.getElementById("blueprint-list"),
  title: document.getElementById("blueprint-title"),
  fieldsList: document.getElementById("fields-list"),
  discardBtn: document.getElementById("discard-rules-btn"),
  saveBtn: document.getElementById("save-rules-btn"),
  tenantSelect: document.getElementById("tenant-select"),
  testBtn: document.getElementById("test-blueprint-btn"),
  testTenantSelect: document.getElementById("test-tenant-select"),
  testCategorySelect: document.getElementById("test-category-select"),
  testFileInput: document.getElementById("test-file-input"),
  runTestBtn: document.getElementById("run-test-btn"),
  cancelTestBtn: document.getElementById("cancel-test-btn"),
  testElapsed: document.getElementById("test-elapsed"),
  testResults: document.getElementById("test-results"),
  testHistoryList: document.getElementById("test-history-list"),
  onNavigate: showContentView,
});

SearchView.init({
  results: document.getElementById("search-results"),
  title: document.getElementById("search-title"),
  saveBtn: document.getElementById("save-search-btn"),
  discardBtn: document.getElementById("discard-search-btn"),
  searchInput: document.getElementById("field-search"),
  onNavigate: showContentView,
});

UsersView.init();
TenantsView.init();
DocumentCategoriesView.init();
AuditLogView.init();

LoginView.init({
  onLogin: async () => {
    const session = Session.get();
    if (routeAfterLogin(session)) {
      await KeysView.load();
      await BlueprintsView.load();
      await TenantContext.load();
    }
  },
});

// --- Sidebar Sections ---
document.querySelectorAll(".nav-section-header").forEach((header) => {
  header.addEventListener("click", () => {
    const section = header.dataset.section;
    const body = document.getElementById(`section-${section}`);
    const arrow = header.querySelector(".nav-arrow");
    const isOpen = !body.classList.contains("hidden");

    if (isOpen) {
      body.classList.add("hidden");
      arrow.textContent = "▸";
      header.classList.remove("active");
    } else {
      body.classList.remove("hidden");
      arrow.textContent = "▾";
      header.classList.add("active");
    }
  });
});



// Manage Documents collapsible toggle
document.getElementById("manage-documents-toggle").addEventListener("click", () => {
  const body = document.getElementById("subsection-documents");
  const arrow = document.getElementById("manage-documents-toggle").querySelector(".nav-arrow");
  const isOpen = !body.classList.contains("hidden");
  if (isOpen) {
    body.classList.add("hidden");
    arrow.textContent = "☰";
  } else {
    body.classList.remove("hidden");
    arrow.textContent = "✕";
  }
});

// Nav items
document.querySelectorAll(".nav-item").forEach((item) => {
  item.addEventListener("click", () => {
    if (BlueprintsView.hasUnsavedChanges() && !confirm("You have unsaved changes. Discard?")) return;
    if (SearchView.isDirty() && !confirm("You have unsaved search changes. Discard?")) return;
    document.querySelectorAll(".nav-item").forEach((i) => i.classList.remove("active"));
    item.classList.add("active");
    showContentView(`view-${item.dataset.view}`);
    if (item.dataset.view === "users-manage") UsersView.load();
    if (item.dataset.view === "tenants-manage") TenantsView.load();
    if (item.dataset.view === "doc-categories-manage") DocumentCategoriesView.load();
    if (item.dataset.view === "audit-log") AuditLogView.load();
    if (item.dataset.view === "test-documents") BlueprintsView.loadTestView();
  });
});

// --- Logout ---
async function logout() {
  const session = Session.get();
  if (session?.accessToken) {
    try {
      await Auth.signOut(session.accessToken);
    } catch {
      // ignore signout errors
    }
  }
  Session.clear();
  BlueprintsView.clearTestHistory();
  LoginView.reset();
  showView(loginView);
}

logoutBtn.addEventListener("click", logout);
document.getElementById("pending-logout-btn").addEventListener("click", logout);

// --- Session expiry ---
Session.onExpire(() => {
  LoginView.reset();
  showView(loginView);
  Toast.show("Session expired due to inactivity");
});


