"""CLI to regenerate env_var_names_generated.py from EnvConfig and AppConfig model fields.

Run whenever fields are added or removed from EnvConfig or AppConfig:

    uv run tasks.py generate-env-names

Commit the updated env_var_names_generated.py alongside any config changes.
"""

from pathlib import Path

import typer

app = typer.Typer()

_OUTPUT = Path(__file__).resolve().parents[1] / "config" / "env_var_names_generated.py"

_HEADER = """\
# DO NOT EDIT - generated by `uv run tasks.py generate-env-names`
# Source of truth: EnvConfig and AppConfig model_fields in env.py
from enum import StrEnum


class EnvVarNames(StrEnum):
"""


@app.command()
def generate() -> None:
    """Regenerate env_var_names_generated.py from EnvConfig and AppConfig model fields."""
    from documentai_api.config.env import AppConfig, EnvConfig

    fields = sorted({**EnvConfig.model_fields, **AppConfig.model_fields})

    lines = [_HEADER]
    for field in fields:
        name = field.upper()
        lines.append(f'    {name} = "{name}"\n')

    _OUTPUT.write_text("".join(lines))
    typer.echo(f"Written {len(fields)} env var names to {_OUTPUT}")


if __name__ == "__main__":
    app()
