"""CLI to regenerate constants_generated.py from infra/document-types folders.

Run whenever document-type folders are added or removed:

    uv run tasks.py generate-categories

Commit the updated constants_generated.py alongside any infra changes.
"""

from pathlib import Path

import typer

app = typer.Typer()

_INFRA_DOCUMENT_TYPES = Path(__file__).resolve().parents[4] / "infra" / "document-types"
_OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "config"
    / "constants_preclassification_category_generated.py"
)

_HEADER = """\
# DO NOT EDIT - generated by `uv run tasks.py generate-categories`
# Source of truth: infra/document-types/ folder names
from enum import StrEnum


class PreclassificationCategory(StrEnum):
"""


@app.command()
def generate() -> None:
    """Regenerate constants_generated.py from infra/document-types folders."""
    folders = sorted(
        p.name
        for p in _INFRA_DOCUMENT_TYPES.iterdir()
        if p.is_dir() and not p.name.startswith(".") and (p / "managed_blueprints.json").exists()
    )

    if not folders:
        typer.echo(f"Error: no folders found in {_INFRA_DOCUMENT_TYPES}", err=True)
        raise typer.Exit(1)

    lines = [_HEADER]
    for folder in folders:
        constant = folder.upper()
        lines.append(f'    {constant} = "{folder}"\n')

    _OUTPUT.write_text("".join(lines))
    typer.echo(f"Written {len(folders)} categories to {_OUTPUT}")


if __name__ == "__main__":
    app()
